//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongbookManagerMaui.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SongbookManagerMaui.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing a shared list.
        /// </summary>
        internal static string AccessingSharedList {
            get {
                return ResourceManager.GetString("AccessingSharedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics can be wrong if the key of the song is changed..
        /// </summary>
        internal static string AddMusicChordsLyricsTutorial {
            get {
                return ResourceManager.GetString("AddMusicChordsLyricsTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the chord field enter only the figures without the lyrics..
        /// </summary>
        internal static string AddMusicChordsTutorial {
            get {
                return ResourceManager.GetString("AddMusicChordsTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When changing the key of the music the chords will be adjusted automatically..
        /// </summary>
        internal static string AddMusicKeysTutorial {
            get {
                return ResourceManager.GetString("AddMusicKeysTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the profile page you will be able to define if you are a singer or not..
        /// </summary>
        internal static string AddMusicProfileTutorial {
            get {
                return ResourceManager.GetString("AddMusicProfileTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the tone field, the singers who have access to the song will be displayed and you will be able to define the tone of each singer..
        /// </summary>
        internal static string AddMusicSingersKeysTutorial {
            get {
                return ResourceManager.GetString("AddMusicSingersKeysTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The song version must be a YouTube, Spotify or Deezer link..
        /// </summary>
        internal static string AddMusicVersionTutorial {
            get {
                return ResourceManager.GetString("AddMusicVersionTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add people.
        /// </summary>
        internal static string AddPeople {
            get {
                return ResourceManager.GetString("AddPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the repertoire information and select the songs that will be part of this repertoire..
        /// </summary>
        internal static string AddRepertoirePageTutorial {
            get {
                return ResourceManager.GetString("AddRepertoirePageTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon.
        /// </summary>
        internal static string Afternoon {
            get {
                return ResourceManager.GetString("Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouShure {
            get {
                return ResourceManager.GetString("AreYouShure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This repertoire will be removed.
        /// </summary>
        internal static string AreYouShureRepertoireRemoved {
            get {
                return ResourceManager.GetString("AreYouShureRepertoireRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This song will be removed from your playlist.
        /// </summary>
        internal static string AreYouShureSongRemoved {
            get {
                return ResourceManager.GetString("AreYouShureSongRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        internal static string AreYouSureYouWantToLogout {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chords.
        /// </summary>
        internal static string Chords {
            get {
                return ResourceManager.GetString("Chords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change password.
        /// </summary>
        internal static string CouldNotChangePassword {
            get {
                return ResourceManager.GetString("CouldNotChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load singers.
        /// </summary>
        internal static string CouldNotLoadSingers {
            get {
                return ResourceManager.GetString("CouldNotLoadSingers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load song.
        /// </summary>
        internal static string CouldNotLoadSong {
            get {
                return ResourceManager.GetString("CouldNotLoadSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load song data.
        /// </summary>
        internal static string CouldNotLoadSongData {
            get {
                return ResourceManager.GetString("CouldNotLoadSongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove repertoire.
        /// </summary>
        internal static string CouldNotRemoveRepertoire {
            get {
                return ResourceManager.GetString("CouldNotRemoveRepertoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove song.
        /// </summary>
        internal static string CouldNotRemoveSong {
            get {
                return ResourceManager.GetString("CouldNotRemoveSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save repertoire.
        /// </summary>
        internal static string CouldNotSaveRepertoire {
            get {
                return ResourceManager.GetString("CouldNotSaveRepertoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save song.
        /// </summary>
        internal static string CouldNotSaveSong {
            get {
                return ResourceManager.GetString("CouldNotSaveSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send repertoire.
        /// </summary>
        internal static string CouldNotSendRepertoire {
            get {
                return ResourceManager.GetString("CouldNotSendRepertoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not sign in.
        /// </summary>
        internal static string CouldNotSignIn {
            get {
                return ResourceManager.GetString("CouldNotSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update repertoire list.
        /// </summary>
        internal static string CouldNotUpdateRepertoireList {
            get {
                return ResourceManager.GetString("CouldNotUpdateRepertoireList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update shared user list.
        /// </summary>
        internal static string CouldNotUpdateSharedUserList {
            get {
                return ResourceManager.GetString("CouldNotUpdateSharedUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update song list.
        /// </summary>
        internal static string CouldNotUpdateSongList {
            get {
                return ResourceManager.GetString("CouldNotUpdateSongList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email with your new password sent.
        /// </summary>
        internal static string EmailWithNewPasswordSent {
            get {
                return ResourceManager.GetString("EmailWithNewPasswordSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the song.
        /// </summary>
        internal static string EnterNameForTheSong {
            get {
                return ResourceManager.GetString("EnterNameForTheSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error resetting password.
        /// </summary>
        internal static string ErrorResettingPassword {
            get {
                return ResourceManager.GetString("ErrorResettingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback for Song Folder Lite.
        /// </summary>
        internal static string FeedbackForSongbook {
            get {
                return ResourceManager.GetString("FeedbackForSongbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give a name.
        /// </summary>
        internal static string GiveAName {
            get {
                return ResourceManager.GetString("GiveAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        internal static string InvalidEmailPassword {
            get {
                return ResourceManager.GetString("InvalidEmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is singer?.
        /// </summary>
        internal static string IsSinger {
            get {
                return ResourceManager.GetString("IsSinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        internal static string Keys {
            get {
                return ResourceManager.GetString("Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 6 months.
        /// </summary>
        internal static string Last6Months {
            get {
                return ResourceManager.GetString("Last6Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        internal static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year.
        /// </summary>
        internal static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyric.
        /// </summary>
        internal static string Lyric {
            get {
                return ResourceManager.GetString("Lyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long.
        /// </summary>
        internal static string MinimumCharacterMessage {
            get {
                return ResourceManager.GetString("MinimumCharacterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to morning.
        /// </summary>
        internal static string Morning {
            get {
                return ResourceManager.GetString("Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most played songs.
        /// </summary>
        internal static string MostPlayedSongs {
            get {
                return ResourceManager.GetString("MostPlayedSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song list.
        /// </summary>
        internal static string MusicList {
            get {
                return ResourceManager.GetString("MusicList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        internal static string Musics {
            get {
                return ResourceManager.GetString("Musics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a new song click on the add button in the lower right corner..
        /// </summary>
        internal static string MusicsAddMusicTutorial {
            get {
                return ResourceManager.GetString("MusicsAddMusicTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are accessing a shared playlist this song will be added to the list of whoever is sharing the playlist..
        /// </summary>
        internal static string MusicsListSharedTutorial {
            get {
                return ResourceManager.GetString("MusicsListSharedTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page, your list of registered or shared access songs is displayed..
        /// </summary>
        internal static string MusicsPageTutorial {
            get {
                return ResourceManager.GetString("MusicsPageTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view or edit a song just select the song..
        /// </summary>
        internal static string MusicsPreviewMusicTutorial {
            get {
                return ResourceManager.GetString("MusicsPreviewMusicTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search bar searches by song name and displays matching songs..
        /// </summary>
        internal static string MusicsSearchTutorial {
            get {
                return ResourceManager.GetString("MusicsSearchTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To share your playlist with others click on the &apos;Share&apos; button in the top menu..
        /// </summary>
        internal static string MusicsShareListTutorial {
            get {
                return ResourceManager.GetString("MusicsShareListTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,&lt;br /&gt;&lt;br /&gt;Your new password is: XXXXXX&lt;br /&gt;&lt;br /&gt;Use this password to log into the application. You can change it within the application.&lt;br /&gt;&lt;br /&gt;Thanks,&lt;br /&gt;&lt;br /&gt;Songbook team.
        /// </summary>
        internal static string NewPasswordEmailBody {
            get {
                return ResourceManager.GetString("NewPasswordEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password for Song Folder Lite.
        /// </summary>
        internal static string NewPasswordEmailSubject {
            get {
                return ResourceManager.GetString("NewPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need an account?.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to night.
        /// </summary>
        internal static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string PasswordsNotMatch {
            get {
                return ResourceManager.GetString("PasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play repertoire.
        /// </summary>
        internal static string PlayRepertoire {
            get {
                return ResourceManager.GetString("PlayRepertoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the edit button at the top of the screen to edit the song information..
        /// </summary>
        internal static string PreviewMusicEditTutorial {
            get {
                return ResourceManager.GetString("PreviewMusicEditTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By changing the key of the song the chords will be adjusted according to the key. This change will not be saved, it will be for viewing only..
        /// </summary>
        internal static string PreviewMusicKeyChangeTutorial {
            get {
                return ResourceManager.GetString("PreviewMusicKeyChangeTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the song has a defined version, a &apos;Play&apos; button will appear on the screen and by clicking this button you will be directed to the music playback platform..
        /// </summary>
        internal static string PreviewMusicPlayTutorial {
            get {
                return ResourceManager.GetString("PreviewMusicPlayTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the remove button to remove the song from the playlist..
        /// </summary>
        internal static string PreviewMusicRemoveTutorial {
            get {
                return ResourceManager.GetString("PreviewMusicRemoveTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are accessing a shared list, the modification will occur in the list of those who gave you access..
        /// </summary>
        internal static string PreviewMusicSharedListTutorial {
            get {
                return ResourceManager.GetString("PreviewMusicSharedListTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the Keys screen, only singers who have a registered key for that song will be displayed..
        /// </summary>
        internal static string PreviewMusicSingersKeysTutorial {
            get {
                return ResourceManager.GetString("PreviewMusicSingersKeysTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the secondary menu it is possible to edit or remove the repertoire..
        /// </summary>
        internal static string PreviewRepertoireEditRemoveTutorial {
            get {
                return ResourceManager.GetString("PreviewRepertoireEditRemoveTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This screen displays the details of the repertoire such as singer, schedules and songs with the singer&apos;s key, if defined in the song..
        /// </summary>
        internal static string PreviewRepertoirePageTutorial {
            get {
                return ResourceManager.GetString("PreviewRepertoirePageTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the top menu it is possible to enter the repertoire playback mode by clicking on the left button..
        /// </summary>
        internal static string PreviewRepertoirePlayTutorial {
            get {
                return ResourceManager.GetString("PreviewRepertoirePlayTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is also possible to reorder the songs in the list. To reorder, select the song you want to change position and then select the position you want it to be in..
        /// </summary>
        internal static string PreviewRepertoireReorderTutorial {
            get {
                return ResourceManager.GetString("PreviewRepertoireReorderTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking on the button on the right it is possible to send this repertoire in text format..
        /// </summary>
        internal static string PreviewRepertoireSendTutorial {
            get {
                return ResourceManager.GetString("PreviewRepertoireSendTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate us.
        /// </summary>
        internal static string RateUs {
            get {
                return ResourceManager.GetString("RateUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoires.
        /// </summary>
        internal static string Repertoires {
            get {
                return ResourceManager.GetString("Repertoires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a new repertoire click on the add button in the lower right corner..
        /// </summary>
        internal static string RepertoiresAddRepertoireTutorial {
            get {
                return ResourceManager.GetString("RepertoiresAddRepertoireTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page displays your list of registered or shared access repertoires..
        /// </summary>
        internal static string RepertoiresPageTutorial {
            get {
                return ResourceManager.GetString("RepertoiresPageTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view or edit a repertoire just select the repertoire..
        /// </summary>
        internal static string RepertoiresPreviewRepertoireTutorial {
            get {
                return ResourceManager.GetString("RepertoiresPreviewRepertoireTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search bar searches by repertoire date or singer and displays the corresponding repertoires..
        /// </summary>
        internal static string RepertoiresSearchTutorial {
            get {
                return ResourceManager.GetString("RepertoiresSearchTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new password will be sent to the email registered to the account. After logging in with this password you can choose a new one in your profile within the application..
        /// </summary>
        internal static string ResetPasswordDescription {
            get {
                return ResourceManager.GetString("ResetPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send repertoire.
        /// </summary>
        internal static string SendRepertoire {
            get {
                return ResourceManager.GetString("SendRepertoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are accessing a shared list you will not be able to share it with other people..
        /// </summary>
        internal static string SharePageNotShareTutorial {
            get {
                return ResourceManager.GetString("SharePageNotShareTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have songs in your list, accessing a shared list will keep your songs, but you won&apos;t see them on the music page unless you unshare..
        /// </summary>
        internal static string SharePagePersonalListTutorial {
            get {
                return ResourceManager.GetString("SharePagePersonalListTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are accessing a shared playlist you will only see the shared playlist and any changes you make will be made to that shared list..
        /// </summary>
        internal static string SharePageSharedListTutorial {
            get {
                return ResourceManager.GetString("SharePageSharedListTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From this page you can share your list with others or manage this sharing by removing people or leaving a share..
        /// </summary>
        internal static string SharePageTutorial {
            get {
                return ResourceManager.GetString("SharePageTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you share your list with others, they will have permission to view and edit that list..
        /// </summary>
        internal static string SharePermissionTutorial {
            get {
                return ResourceManager.GetString("SharePermissionTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share your songs.
        /// </summary>
        internal static string ShareYourSongs {
            get {
                return ResourceManager.GetString("ShareYourSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singer.
        /// </summary>
        internal static string Singer {
            get {
                return ResourceManager.GetString("Singer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs for.
        /// </summary>
        internal static string SongsFor {
            get {
                return ResourceManager.GetString("SongsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by alphabet.
        /// </summary>
        internal static string SortByAlphabet {
            get {
                return ResourceManager.GetString("SortByAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by newest.
        /// </summary>
        internal static string SortByMostRecent {
            get {
                return ResourceManager.GetString("SortByMostRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by oldest.
        /// </summary>
        internal static string SortByOldest {
            get {
                return ResourceManager.GetString("SortByOldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Sharing.
        /// </summary>
        internal static string StopSharing {
            get {
                return ResourceManager.GetString("StopSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucess.
        /// </summary>
        internal static string Sucess {
            get {
                return ResourceManager.GetString("Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no registered or shared access singers..
        /// </summary>
        internal static string ThereAreNoRegisteredSharedAccessSingers {
            get {
                return ResourceManager.GetString("ThereAreNoRegisteredSharedAccessSingers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no singers with saved keys for this song..
        /// </summary>
        internal static string ThereAreNoSingersWithSavedKeysForThisSong {
            get {
                return ResourceManager.GetString("ThereAreNoSingersWithSavedKeysForThisSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user will be removed from your share list.
        /// </summary>
        internal static string ThisUserWillBeRemovedFromYourShareList {
            get {
                return ResourceManager.GetString("ThisUserWillBeRemovedFromYourShareList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform search.
        /// </summary>
        internal static string UnablePerformSearch {
            get {
                return ResourceManager.GetString("UnablePerformSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register user.
        /// </summary>
        internal static string UnableRegisterUser {
            get {
                return ResourceManager.GetString("UnableRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove share.
        /// </summary>
        internal static string UnableRemoveShare {
            get {
                return ResourceManager.GetString("UnableRemoveShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to share song list.
        /// </summary>
        internal static string UnableShareSongList {
            get {
                return ResourceManager.GetString("UnableShareSongList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load keys.
        /// </summary>
        internal static string UnableToLoadKeys {
            get {
                return ResourceManager.GetString("UnableToLoadKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to unshare.
        /// </summary>
        internal static string UnableToUnshare {
            get {
                return ResourceManager.GetString("UnableToUnshare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered user.
        /// </summary>
        internal static string UnregisteredUser {
            get {
                return ResourceManager.GetString("UnregisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already accessing a shared song list.
        /// </summary>
        internal static string UserAlreadyAccessingSharedSongList {
            get {
                return ResourceManager.GetString("UserAlreadyAccessingSharedSongList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already registered.
        /// </summary>
        internal static string UserAlreadyRegistered {
            get {
                return ResourceManager.GetString("UserAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to send the repertoire?.
        /// </summary>
        internal static string WantToSendRepertoire {
            get {
                return ResourceManager.GetString("WantToSendRepertoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will no longer have access to this song list.
        /// </summary>
        internal static string YouWillNoLongerHaveAccessToThisSongList {
            get {
                return ResourceManager.GetString("YouWillNoLongerHaveAccessToThisSongList", resourceCulture);
            }
        }
    }
}
